# ################################################################### #
#                                                                     #                
# Section -> MESSAGES                                                 #
#                                                                     # 
# All messages are configurable.                                      #
# Below you will be able to modify everything to your needs.          #
# You can even use a list to send messages.                           #
#                                                                     #
# ################################################################### # 

Messages:
  No-Permission: '&cYou don''t have permission to execute this command'
#  No-Permission:
#    - '&cYou don''t have permission to execute this command.'
#    - '&cPlease contact an admin if you think this is a mistake.'
  Target-Offline: '&6%target% &cdoesn''t seem to be online.'
  Target-Inventory-Closed: '&cIt seems that &6%target%''s &cdupe machine is not opened.'
  Item-Name-Invalid: '&cThe name &6%id% &cis an invalid one, consider changing it.'
  Item-Already-Banned: '&cThe item you''re attempting to add is already banned.'
  Item-Type-Already-Banned: '&cThe item type you''re attempting to add is fully banned.'
  Item-Blacklisted: '&7You have successfully &cblacklisted the &3%item% &7with id &e%id%'
  Item-UnBlacklisted: '&7You have successfully &aunblacklisted id &e%id%'
  ID-Not-Exist: '&7The item with id &e%id% &7doesn''t seem to be blacklisted.'
  ID-Already-Exist: '&7The id &e%id% &7is already taken, try something different.'
  Inventory-Full: '&cYour inventory was full, dropping leftovers to the floor.'
  Plugin-Reloaded: '&aThe plugin has been reloaded successfuly!'
  No-Item-In-Hand: '&cYou must be holding an item in order to ban it!'
  Plugin-Disabling: '&cThe plugin is being disabled, closing your inventory...'
  View-Self: '&cYou can''t view yourself! Try again with a different user.'
  Unviewable: '&e%target%&c''s machine is not viewable: &e%machine%'
  Default-Machine-Unchangeable: '&cYou may not do this with the default machine!'
  Machine-Not-Exist: '&cThe machine &e%machine% &cdoesn''t seem to exist.'
  User-Already-In-Machine: '&cThe user &e%user% &cis already allowed for the machine &e%machine%'
  Rank-Already-In-Machine: '&cThe rank &e%rank% &cis already allowed for the machine &e%machine%'
  User-Already-Not-In-Machine: '&cThe user &e%user% &cis already disallowed for the machine &e%machine%'
  Rank-Already-Not-In-Machine: '&cThe rank &e%rank% &cis already disallowed for the machine &e%machine%'
  User-Added-In-Machine: '&aThe user &d%user% &ahas been added in the &d%machine% &amachine.'
  User-Removed-From-Machine: '&cThe user &e%user% &chas been removed from the &e%machine% &cmachine.'
  Rank-Added-In-Machine: '&aThe rank &d%rank% &ahas been added in the &d%machine% &amachine.'
  Rank-Removed-From-Machine: '&cThe rank &e%rank% &chas been removed from the &e%machine% &cmachine.'
  Unknown-Arguement: 
    - '&cIt seems that the command you typed is wrong.'
    - '&cHave you made a typo?'
  Help-Format:
    - '&7&m-----------------------------'
    - ''
    - '&3/dupe &7- &oOpens the dupe machine.'
    - '&3/dupe add <id> &7- &oBlacklists a holding item.'
    - '&3/dupe remove <id> &7- &oUnblacklists an id.'
    - '&3/dupe help &7- &oShows this menu.'
    - '&3/dupe reload &7- &oReloads the plugin.' 
    - '&3/dupe &9<player> &7- &oViews a players dupe machine.'
    - '&3/dupe &9allowplayer <player> <machine id> &7- &oAllows a player to use a machine.'
    - '&3/dupe &9disallowplayer <player> <machine id> &7- &oDisallows a player from using a machine.'
    - '&3/dupe &9allowrank <rank> <machine id> &7- &oAllows a rank to use a machine.'
    - '&3/dupe &9disallowrank <rank> <machine id> &7- &oDisallows a rank from using a machine.'
    - ''
    - '&7&m-----------------------------'
    
    
    

