name: DupeMachineX
author: Shin1gamiX
version: 0.9
main: net.shin1gamix.dupemachine.Core
website: https://github.com/Cod1ngBugz/DupeMachineX
description: Allows you to duplicate items in a GUI.
depend: [Vault]

commands:
  dupemachinex:
    usage: /<command>
    aliases: [dupemachine, dmx, duplication, dupe, duplicate, dupex, dpx, duplicationx, duplicatex]
    description: The main command.

permissions:
  dupemachinex.*:
    description: Gives access to all DupeMachineX commands.
    children:
      dupemachinex.use: true
      dupemachinex.help: true
      dupemachinex.view: true
      dupemachinex.reload: true
      dupemachinex.blacklist: true
      dupemachinex.unblacklist: true
      dupemachinex.disallow.player: true
      dupemachinex.allow.player: true
      dupemachinex.disallow.rank: true
      dupemachinex.allow.rank: true
      dupemachinex.update: true
  dupemachinex.use:
    description: Allows you to open the duplication machine.
    default: op
  dupemachinex.update:
    description: Notify all operators about plugin updates!
    default: op
  dupemachinex.reload:
    description: Allows you to reload the plugin.
    default: op
  dupemachinex.help:
    description: Allows you to use the duplication help command.
    default: op
  dupemachinex.view:
    description: Allows you to view another players duplication machine.
    default: op
  dupemachinex.blacklist:
    description: Allows you to blacklist certain items.
    default: op
  dupemachinex.unblacklist:
    description: Allows you to unblacklist already blacklisted items.
    default: op
  dupemachinex.disallow.player:
    description: Allows you to disallow a player from a machine.
    default: op
  dupemachinex.allow.player:
    description: Allows you to give access to a player for a machine.
    default: op
  dupemachinex.disallow.rank:
    description: Allows you to disallow a rank from a machine.
    default: op
  dupemachinex.allow.rank:
    description: Allows you to give access to a rank for a machine.
    default: op